version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:password@db:5432/dbname # Update with your PostgreSQL configuration

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname

